# Generated by Django 2.2.5 on 2019-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_user',
            field=models.BooleanField(default=False, help_text='指明是否是API用户', verbose_name='API用户'),
        ),
    ]
