# Generated by Django 2.2.6 on 2019-11-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190924_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254, verbose_name='发送者')),
                ('receiver', models.EmailField(max_length=254, verbose_name='接收者')),
                ('message', models.CharField(max_length=1000, verbose_name='邮件内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='api_user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='', max_length=255, verbose_name='公司/单位'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
    ]
