# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=6789)),
                ('uuid', models.CharField(max_length=100)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute.Center')),
            ],
            options={
                'verbose_name': '存储集群',
                'verbose_name_plural': '1_存储集群',
            },
        ),
        migrations.CreateModel(
            name='CephPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Image Pool'), (2, 'Volume Pool')])),
                ('enable', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.CephHost')),
            ],
            options={
                'verbose_name': '资源池',
                'verbose_name_plural': '2_资源池',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cephpool',
            unique_together=set([('host', 'pool')]),
        ),
    ]
