# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=6789)),
                ('uuid', models.CharField(max_length=100)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('backend', models.CharField(choices=[('ceph', 'CEPH'), ('gfs', 'GFS'), ('local', 'LOCAL')], default='ceph', max_length=50)),
                ('hosts_xml', models.TextField(help_text='用于设置镜像xml中disk/source元素的子节点host信息', null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute.Center')),
            ],
            options={
                'verbose_name': '存储集群',
                'verbose_name_plural': '1_存储集群',
            },
        ),
        migrations.CreateModel(
            name='CephPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Image Pool'), (2, 'Volume Pool')])),
                ('enable', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.CephHost')),
            ],
            options={
                'verbose_name': '存储卷',
                'verbose_name_plural': '2_存储卷',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cephpool',
            unique_together=set([('host', 'pool')]),
        ),
    ]
