# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBCephQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(help_text='单位MB', verbose_name='集群总容量')),
                ('volume', models.IntegerField(help_text='单位MB', verbose_name='云硬盘容量')),
                ('cephpool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.CephPool', verbose_name='存储卷')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compute.Group', verbose_name='计算集群')),
            ],
            options={
                'verbose_name': 'Ceph云硬盘配额',
                'verbose_name_plural': '2_Ceph云硬盘配额',
            },
        ),
        migrations.CreateModel(
            name='DBCephVolume',
            fields=[
                ('uuid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('vm', models.CharField(blank=True, max_length=200, null=True)),
                ('attach_time', models.DateTimeField(blank=True, null=True)),
                ('dev', models.CharField(blank=True, max_length=100, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('cephpool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.CephPool')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compute.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ceph云硬盘',
                'verbose_name_plural': '1_Ceph云硬盘',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dbcephquota',
            unique_together=set([('group', 'cephpool')]),
        ),
    ]
