# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20180622_1422'),
        ('volume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcephquota',
            name='cephpool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.CephPool', verbose_name='存储卷'),
        ),
        migrations.AlterField(
            model_name='dbcephquota',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compute.Group', verbose_name='计算集群'),
        ),
    ]
