# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('ipv4', models.GenericIPAddressField(unique=True)),
                ('vmid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': '1_IP地址',
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.CharField(max_length=100)),
                ('br', models.CharField(max_length=50)),
                ('enable', models.BooleanField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('subnetip', models.GenericIPAddressField(blank=True, null=True)),
                ('netmask', models.GenericIPAddressField(blank=True, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('dnsserver', models.GenericIPAddressField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='用于在页面中的显示顺序，数值越小越靠前。', verbose_name='排序')),
            ],
            options={
                'verbose_name': '子网',
                'verbose_name_plural': '2_子网',
            },
        ),
        migrations.CreateModel(
            name='VlanType',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='类型编号')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('order', models.IntegerField(default=0, help_text='用于在页面中的显示顺序，数值越小越靠前。', verbose_name='排序')),
            ],
            options={
                'verbose_name': '子网类型',
                'verbose_name_plural': '3_子网类型',
            },
        ),
        migrations.AddField(
            model_name='vlan',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.VlanType'),
        ),
        migrations.AddField(
            model_name='macip',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Vlan'),
        ),
    ]
