# Generated by Django 2.2.6 on 2019-10-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '网络类型',
                'verbose_name_plural': '05_网络类型',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='VLAN描述')),
                ('br', models.CharField(max_length=50, verbose_name='网桥名')),
                ('subnet_ip', models.GenericIPAddressField(verbose_name='子网IP')),
                ('net_mask', models.GenericIPAddressField(blank=True, null=True, verbose_name='子网掩码')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('dns_server', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS服务IP')),
                ('enable', models.BooleanField(default=True, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('net_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_set', to='network.NetworkType', verbose_name='网络类型')),
            ],
            options={
                'verbose_name': 'VLAN子网',
                'verbose_name_plural': '05_VLAN子网',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MacIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=17, unique=True, verbose_name='MAC地址')),
                ('ipv4', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('used', models.BooleanField(default=False, help_text='是否已分配给虚拟机使用', verbose_name='被使用')),
                ('enable', models.BooleanField(default=True, help_text='是否可以被分配使用', verbose_name='开启使用')),
                ('desc', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('vlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macips', to='network.Vlan', verbose_name='VLAN子网')),
            ],
            options={
                'verbose_name': 'MAC IP地址',
                'verbose_name_plural': '07_MAC IP地址',
            },
        ),
    ]
