# Generated by Django 2.2.8 on 2019-12-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20191016_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='dns_server',
            field=models.CharField(max_length=255, verbose_name='DNS服务IP'),
        ),
    ]
