# Generated by Django 2.2.13 on 2020-06-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0004_host_real_cpu'),
        ('network', '0003_auto_20191225_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='center',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_set', to='compute.Center', verbose_name='分中心'),
        ),
    ]
