# Generated by Django 2.2.14 on 2020-08-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_vlan_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='tag',
            field=models.SmallIntegerField(choices=[(0, '私网'), (1, '公网')], default=0, verbose_name='网络标签'),
        ),
    ]
