# Generated by Django 2.2.16 on 2020-12-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0005_remove_host_vlans'),
        ('network', '0005_vlan_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='center',
        ),
        migrations.RemoveField(
            model_name='vlan',
            name='net_type',
        ),
        migrations.AddField(
            model_name='vlan',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_set', to='compute.Group', verbose_name='宿主机组'),
        ),
        migrations.DeleteModel(
            name='NetworkType',
        ),
    ]
