# Generated by Django 3.2.13 on 2023-05-25 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20220919_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='vlan_id',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vlan id'),
        ),
    ]
