# Generated by Django 3.2.13 on 2023-07-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_vlan_vlan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macip',
            options={'ordering': ['id'], 'verbose_name': 'MAC IP地址', 'verbose_name_plural': '07_MAC IP地址'},
        ),
    ]
