# Generated by Django 3.2.13 on 2023-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_macip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='iptype',
            field=models.CharField(choices=[('ipv4', 'ipv4'), ('ipv6', 'ipv6')], default='ipv4', max_length=4, verbose_name='IP类型'),
        ),
    ]
