# Generated by Django 3.2.13 on 2023-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_macip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='macip',
            name='ipv6type',
            field=models.BooleanField(default=False, verbose_name='ipv6类型地址'),
        ),
    ]
