# Generated by Django 3.2.13 on 2023-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20230727_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='macip',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IPv6地址'),
        ),
    ]
