# Generated by Django 4.2.9 on 2024-09-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_shieldvlan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='image_specialized',
        ),
    ]
