# Generated by Django 2.2.14 on 2020-08-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='client.ovpn', help_text='client.ovpn、  ca.crt', max_length=255, verbose_name='文件名')),
                ('tag', models.SmallIntegerField(choices=[(1, 'CA证书'), (2, '配置文件')], default=2, verbose_name='标签')),
                ('content', models.TextField(default='', verbose_name='文件内容')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'VPN配置文件',
                'verbose_name_plural': 'VPN配置文件',
                'ordering': ['-id'],
            },
        ),
    ]
