# Generated by Django 3.2.13 on 2023-02-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_vpnconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnauth',
            name='expired_time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='vpnauth',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
