# Generated by Django 3.2.13 on 2023-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_auto_20230203_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnauth',
            name='expired_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间'),
        ),
    ]
