# Generated by Django 3.2.13 on 2023-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_alter_vpnauth_expired_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('timeunix', models.PositiveBigIntegerField(verbose_name='登录时间戳')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='登出时间')),
                ('server_local_ip', models.GenericIPAddressField(verbose_name='服务器IP地址')),
                ('client_ip', models.GenericIPAddressField(verbose_name='客户端IP地址')),
                ('client_trusted_ip', models.GenericIPAddressField(verbose_name='客户端公网IP地址')),
                ('client_trusted_port', models.IntegerField(verbose_name='客户端公网端口')),
                ('bytes_received', models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='上行流量')),
                ('bytes_sent', models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='下行流量')),
            ],
            options={
                'verbose_name': 'VPN日志记录',
                'verbose_name_plural': 'VPN日志记录',
                'ordering': ['-id'],
            },
        ),
    ]
