# Generated by Django 4.2.9 on 2024-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_vpnlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlog',
            name='vpn_server_ip',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='VPN服务IP'),
        ),
    ]
