# Generated by Django 4.2.9 on 2024-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_vpnlog_vpn_server_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VPNConfig',
        ),
    ]
