# Generated by Django 2.2.6 on 2019-10-15 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compute', '0001_initial'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='虚拟机UUID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('vcpu', models.IntegerField(verbose_name='CPU数')),
                ('mem', models.IntegerField(verbose_name='内存大小')),
                ('disk', models.CharField(help_text='vm自己的系统盘，保存于ceph中的rdb文件名称', max_length=100, unique=True, verbose_name='系统盘名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('xml', models.TextField(help_text='定义虚拟机的当前的XML内容', verbose_name='虚拟机当前的XML')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute.Host', verbose_name='宿主机')),
                ('image', models.ForeignKey(help_text='创建此虚拟机时使用的源系统镜像，disk从image复制', on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='源镜像')),
                ('mac_ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ip_vm', to='network.MacIP', verbose_name='MAC IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vms', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '虚拟机',
                'verbose_name_plural': '11_虚拟机',
            },
        ),
    ]
