# Generated by Django 2.2.6 on 2019-11-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20191024_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmArchive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='虚拟机UUID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('vcpu', models.IntegerField(verbose_name='CPU数')),
                ('mem', models.IntegerField(verbose_name='内存大小')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('br', models.CharField(blank=True, default='', max_length=50, verbose_name='网桥名')),
                ('mac', models.CharField(blank=True, default='', max_length=50, verbose_name='MAC地址')),
                ('ipv4', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('disk', models.CharField(help_text='vm自己的系统盘，保存于ceph中的rdb文件名称', max_length=100, verbose_name='系统盘名称')),
                ('image_id', models.IntegerField(verbose_name='系统镜像id')),
                ('image_parent', models.CharField(help_text='虚拟机系统盘镜像的父镜像', max_length=255, verbose_name='父镜像')),
                ('xml', models.TextField(help_text='定义虚拟机的当前的XML内容', verbose_name='虚拟机当前的XML')),
                ('ceph_id', models.IntegerField(verbose_name='CEPH集群id')),
                ('ceph_pool', models.CharField(blank=True, default='', max_length=100, verbose_name='CEPH POOL')),
                ('center_id', models.IntegerField(blank=True, default=0, verbose_name='数据中心ID')),
                ('center_name', models.CharField(blank=True, default='', max_length=100, verbose_name='数据中心')),
                ('group_id', models.IntegerField(blank=True, default=0, verbose_name='宿主机组ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='宿主机组')),
                ('host_id', models.IntegerField(blank=True, default=0, verbose_name='宿主机ID')),
                ('host_ipv4', models.CharField(blank=True, default='', max_length=50, verbose_name='宿主机IP')),
                ('user', models.CharField(blank=True, default='', max_length=200, verbose_name='创建者')),
                ('create_time', models.DateTimeField(verbose_name='VM创建日期')),
                ('archive_time', models.DateTimeField(auto_now_add=True, verbose_name='VM归档日期')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '虚拟机归档记录',
                'verbose_name_plural': '虚拟机归档表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VmLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='日志内容')),
                ('about', models.SmallIntegerField(choices=[(0, '普通'), (1, '有关MAC IP资源'), (2, '有关MEM CPU资源'), (3, '有关系统盘资源'), (4, '有关虚拟机元数据'), (5, '有关虚拟机归档记录'), (6, '有关宿主机已创建虚拟机数量'), (7, '有关虚拟硬盘'), (8, '有关GPU')], default=0, verbose_name='关于日志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '虚拟机相关错误日志',
                'verbose_name_plural': '虚拟机相关错误日志',
                'ordering': ['-id'],
            },
        ),
    ]
