# Generated by Django 2.2.7 on 2019-11-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0001_initial'),
        ('vms', '0003_vmarchive_vmlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmDiskSnap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('disk', models.CharField(max_length=100, verbose_name='虚拟机系统盘')),
                ('snap', models.CharField(max_length=100, verbose_name='系统盘CEPH快照')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('remarks', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('ceph_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ceph.CephPool', verbose_name='CEPH POOL')),
                ('vm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys_disk_snaps', to='vms.Vm', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '虚拟机系统盘快照',
                'verbose_name_plural': '虚拟机系统盘快照',
                'ordering': ['-id'],
            },
        ),
    ]
