# Generated by Django 2.2.10 on 2020-06-12 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_vm_init_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vcpus', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='虚拟CPU数')),
                ('ram', models.IntegerField(help_text='单位MB', validators=[django.core.validators.MinValueValidator(512)], verbose_name='内存')),
                ('public', models.BooleanField(default=True, help_text='非公开的普通用户不可见，超级用户可见', verbose_name='是否公开')),
                ('enable', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '虚拟机硬件配置样式',
                'verbose_name_plural': '虚拟机硬件配置样式',
                'ordering': ['vcpus'],
            },
        ),
    ]
