# Generated by Django 2.2.16 on 2020-11-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0008_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmarchive',
            name='host_released',
            field=models.BooleanField(default=True, help_text='标记宿主机上的vm是否删除清理', verbose_name='宿主机资源是否释放'),
        ),
    ]
