# Generated by Django 3.2.13 on 2022-07-13 11:29

import django.core.validators
from django.db import migrations, models

def update_vm_unit_mb_to_gb(apps, schema_editor):
    Vm = apps.get_model("vms","Vm")
    vms = Vm.objects.all()
    for vm in vms:
        vm.mem = vm.mem / 1024
        vm.save()
    print('changed vm unit', len(vms), 'records')


def update_flavor_unit_mb_to_gb(apps, schema_editor):
    Flavor = apps.get_model("vms","Flavor")
    flavors = Flavor.objects.all()
    for flavor in flavors:
        flavor.ram = flavor.ram/1024
        flavor.save()
    print('changed flavor unit ', len(flavors), 'records')

class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_auto_20220120_1607'),
    ]

    operations = [
        migrations.RunPython(update_vm_unit_mb_to_gb),
        migrations.RunPython(update_flavor_unit_mb_to_gb),
        migrations.AlterField(
            model_name='flavor',
            name='ram',
            field=models.IntegerField(help_text='单位GB', validators=[django.core.validators.MinValueValidator(1)], verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='mem',
            field=models.IntegerField(help_text='单位GB', verbose_name='内存大小'),
        ),
    ]
