# Generated by Django 3.2.13 on 2023-05-08 01:18

from django.db import migrations


def fill_image_fields(apps, schema_editor):
    vm_cls = apps.get_model('vms', 'Vm')
    vm_qs = vm_cls.objects.select_related('image').all()
    for vm in vm_qs:
        image = vm.image
        vm.image_name = image.name
        vm.image_parent = image.base_image
        vm.image_snap = image.snap
        vm.image_size = image.size
        vm.sys_type = image.sys_type
        vm.version = image.version
        vm.release = image.release
        vm.architecture = image.architecture
        vm.boot_mode = image.boot_mode
        vm.nvme_support = image.nvme_support
        vm.ceph_pool_id = image.ceph_pool_id
        vm.default_user = image.default_user
        vm.default_password = image.default_password
        vm.image_desc = image.desc
        if image.xml_tpl:
            vm.image_xml_tpl = image.xml_tpl.xml

        vm.save(update_fields=[
            'image_name', 'image_parent', 'image_snap', 'image_size', 'sys_type', 'version', 'release',
            'architecture', 'boot_mode', 'nvme_support', 'ceph_pool_id', 'default_user', 'default_password',
            'image_desc', 'image_xml_tpl'
        ])


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0014_auto_20230508_0908'),
    ]

    operations = [
        migrations.RunPython(fill_image_fields, reverse_code=do_nothing),
    ]
