# Generated by Django 3.2.13 on 2023-05-08 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20230222_1228'),
        ('vms', '0015_auto_20230508_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='创建此虚拟机时使用的源系统镜像，disk从image复制', null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.image', verbose_name='源镜像'),
        ),
    ]
