# Generated by Django 3.2.13 on 2023-07-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_vlan_vlan_id'),
        ('vms', '0017_auto_20230612_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentsIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ip', models.OneToOneField(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_ip', to='network.macip', verbose_name='附加MACIP')),
                ('vm', models.ForeignKey(blank=True, db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vm_attach', to='vms.vm', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '虚拟机附加ip',
                'verbose_name_plural': '虚拟机附加ip',
                'ordering': ['id'],
            },
        ),
    ]
