# Generated by Django 4.2.9 on 2024-02-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0018_attachmentsip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, default=0, verbose_name='状态码')),
                ('method', models.CharField(blank=True, default='', max_length=32, verbose_name='请求方法')),
                ('full_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='请求路径')),
                ('message', models.TextField(blank=True, default='', verbose_name='日志信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='请求用户')),
            ],
            options={
                'verbose_name': '接口错误日志记录表',
                'verbose_name_plural': '接口错误日志记录表',
                'db_table': 'error_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
