# Generated by Django 4.2.9 on 2024-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0019_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmlog',
            name='error_handler',
            field=models.BooleanField(default=False, verbose_name='解决'),
        ),
    ]
