# Generated by Django 4.2.9 on 2024-10-11 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms', '0020_vmlog_error_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmSharedUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('readonly', '只读'), ('readwrite', '读写')], default='readonly', max_length=16, verbose_name='共享权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.vm', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '虚拟机的共享用户',
                'verbose_name_plural': '虚拟机的共享用户',
                'db_table': 'vm_shared_user',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='vm',
            name='shared_users',
            field=models.ManyToManyField(related_name='user_shared_vms_set', through='vms.VmSharedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vmshareduser',
            constraint=models.UniqueConstraint(fields=('vm', 'user'), name='unique_shared_vm_user'),
        ),
    ]
