# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cephpool_id', models.IntegerField()),
                ('disk', models.CharField(max_length=100)),
                ('snap', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('vm_uuid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '虚拟机系统盘快照',
                'verbose_name_plural': '4_虚拟机系统盘快照',
            },
        ),
    ]
