# Generated by Django 2.2.6 on 2019-10-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base_image',
            field=models.CharField(default='', help_text='用于创建镜像快照', max_length=200, verbose_name='父镜像'),
        ),
    ]
