# Generated by Django 2.2.7 on 2019-11-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0002_auto_20191016_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sys_type',
            field=models.SmallIntegerField(choices=[(1, 'Windows'), (2, 'Linux'), (3, 'Unix'), (4, 'MacOS'), (5, 'Android'), (6, '其他')], default=6, verbose_name='系统类型'),
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.SmallIntegerField(choices=[(1, '基础镜像'), (2, '用户镜像')], default=2, verbose_name='镜像标签'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_set', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
