# Generated by Django 3.2.5 on 2021-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20191122_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='default_password',
            field=models.CharField(default='cnic.cn', max_length=32, verbose_name='系统默认登录密码'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_user',
            field=models.CharField(default='root', max_length=32, verbose_name='系统默认登录用户名'),
        ),
    ]
