# Generated by Django 3.2.5 on 2022-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20210709_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=0, help_text='image size不是整Gb大小，要向上取整，如1.1GB向上取整为2Gb', verbose_name='镜像大小（Gb）'),
        ),
    ]
