# Generated by Django 3.2.13 on 2022-09-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0007_auto_20220919_1608'),
        ('network', '0007_auto_20220919_1608'),
        ('image', '0006_auto_20220424_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='vm_host',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compute.host', verbose_name='宿主机'),
        ),
        migrations.AddField(
            model_name='image',
            name='vm_mac_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.macip', verbose_name='MAC IP'),
        ),
        migrations.AddField(
            model_name='image',
            name='vm_mem',
            field=models.IntegerField(blank=True, help_text='单位GB', null=True, verbose_name='内存大小'),
        ),
        migrations.AddField(
            model_name='image',
            name='vm_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='虚拟机UUID'),
        ),
        migrations.AddField(
            model_name='image',
            name='vm_vcpu',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU数'),
        ),
    ]
