# Generated by Django 3.2.13 on 2023-02-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0008_auto_20230203_0831'),
        ('network', '0007_auto_20220919_1608'),
        ('image', '0007_auto_20220919_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='create_newsnap',
        ),
        migrations.AlterField(
            model_name='image',
            name='vm_host',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compute.host', verbose_name='宿主机'),
        ),
        migrations.AlterField(
            model_name='image',
            name='vm_mac_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.macip', verbose_name='MAC IP'),
        ),
    ]
