# Generated by Django 3.2.13 on 2023-02-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20230203_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='architecture',
            field=models.SmallIntegerField(choices=[(1, 'x86-64'), (2, 'i386'), (3, 'arm-64'), (4, 'unknown')], default=1, verbose_name='系统架构'),
        ),
        migrations.AddField(
            model_name='image',
            name='boot_mode',
            field=models.SmallIntegerField(choices=[(1, 'UEFI'), (2, 'BIOS')], default=2, verbose_name='系统启动方式'),
        ),
        migrations.AddField(
            model_name='image',
            name='nvme_support',
            field=models.BooleanField(default=False, verbose_name='支持NVME设备'),
        ),
        migrations.AddField(
            model_name='image',
            name='release',
            field=models.SmallIntegerField(choices=[(1, 'Windows Desktop'), (2, 'Windows Server'), (3, 'Ubuntu'), (4, 'Fedora'), (5, 'Centos'), (7, 'Rocky'), (6, 'Unknown')], default=5, verbose_name='系统发行版本'),
        ),
        migrations.AlterField(
            model_name='image',
            name='version',
            field=models.CharField(max_length=100, verbose_name='系统发行编号'),
        ),
    ]
