# Generated by Django 4.2.9 on 2024-06-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20230222_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmxmltemplate',
            name='max_cpu_socket',
            field=models.IntegerField(blank=True, default=0, verbose_name='cpu 颗数'),
        ),
    ]
