# Generated by Django 4.2.9 on 2024-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_vmxmltemplate_max_cpu_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mirror_image_market',
            field=models.BooleanField(default=False, help_text='镜像市场下载的镜像', verbose_name='镜像市场'),
        ),
        migrations.CreateModel(
            name='MirrorImageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirror_image_name', models.CharField(max_length=100, verbose_name='镜像名称')),
                ('mirror_image_sys_type', models.CharField(default='Linux', help_text='Windows、Linux、Unix、MacOS、Android、其他', max_length=100, verbose_name='系统类型')),
                ('mirror_image_version', models.CharField(default='stream 9', max_length=100, verbose_name='系统发行编号')),
                ('mirror_image_release', models.CharField(default='Centos', help_text='Centos、Ubuntu、Windows Desktop、Windows Server、Fedora、Rocky、Unknown', max_length=100, verbose_name='系统发行版本')),
                ('mirror_image_architecture', models.CharField(default='x86-64', help_text='x86-64、i386、arm-64、unknown', max_length=100, verbose_name='系统架构')),
                ('mirror_image_boot_mode', models.CharField(default='BIOS', help_text='BIOS、UEFI', max_length=100, verbose_name='系统启动方式')),
                ('mirror_image_base_image', models.CharField(default='', help_text='导入ceph的镜像需要的名称', max_length=200, verbose_name='镜像')),
                ('mirror_image_enable', models.BooleanField(default=True, help_text='镜像导入成功后，会启用镜像，否则不会启用', verbose_name='启用')),
                ('mirror_image_xml_tpl', models.IntegerField(help_text='找到xml模板的数据,填写id', verbose_name='xml模板')),
                ('user', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, default=None, null=True, verbose_name='描述')),
                ('mirror_image_default_user', models.CharField(default='root', max_length=32, verbose_name='系统默认登录用户名')),
                ('mirror_image_default_password', models.CharField(default='cnic.cn', max_length=32, verbose_name='系统默认登录密码')),
                ('mirror_image_size', models.IntegerField(default=0, help_text='image size不是整Gb大小，要向上取整，如1.1GB向上取整为2Gb', verbose_name='镜像大小（Gb）')),
                ('operate', models.SmallIntegerField(choices=[(1, '下载'), (2, '上传')], default=1, verbose_name='操作')),
                ('update_local_path', models.CharField(default='/00_data/mirror_image/upload/', max_length=100, verbose_name='上传本地存储路径')),
                ('download_local_path', models.CharField(default='/00_data/mirror_image/downnlod/', max_length=100, verbose_name='下载本地存储路径')),
                ('mirrors_image_service_url', models.CharField(max_length=255, verbose_name='公共镜像地址')),
                ('status', models.SmallIntegerField(choices=[(1, '下载中'), (2, '下载完成'), (3, '上传中'), (4, '上传完成'), (5, '上传失败'), (6, '下载失败'), (7, '无')], default=1, verbose_name='任务状态')),
                ('import_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='导入开始时间')),
                ('import_date_complate', models.DateTimeField(blank=True, default=None, null=True, verbose_name='导入完成时间')),
                ('export_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='导出开始时间')),
                ('export_date_complate', models.DateTimeField(blank=True, default=None, null=True, verbose_name='导出完成时间')),
                ('error_msg', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='错误信息')),
                ('bucket_name', models.CharField(default='', max_length=255, verbose_name='存储桶名称')),
                ('file_path', models.CharField(default='', max_length=500, verbose_name='文件路径')),
                ('token', models.CharField(default='', max_length=500, verbose_name='存储桶token')),
                ('local_hostname', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='本地hosnname')),
                ('download_or_upload_status', models.BooleanField(default=False, verbose_name='下载或上传完成')),
                ('create_os_image', models.BooleanField(default=False, verbose_name='创建操作系统镜像完成')),
            ],
            options={
                'verbose_name': '公共镜像任务表',
                'verbose_name_plural': '公共镜像任务表',
                'db_table': 'app_image_mirror_image_task',
                'ordering': ['-id'],
                'unique_together': {('mirror_image_name', 'mirror_image_version', 'operate')},
            },
        ),
    ]
