# Generated by Django 4.2.9 on 2024-07-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_image_mirror_image_market_mirrorimagetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirrorimagetask',
            name='xml_tpl_search',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='xml模板关键字查询'),
        ),
        migrations.AlterField(
            model_name='mirrorimagetask',
            name='mirror_image_xml_tpl',
            field=models.IntegerField(blank=True, default=0, help_text='找到xml模板的数据,填写id', null=True, verbose_name='xml模板'),
        ),
    ]
