# Generated by Django 4.2.9 on 2024-07-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_mirrorimagetask_xml_tpl_search_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mirrorimagetask',
            unique_together=set(),
        ),
    ]
