# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBGPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='format:<domain>:<bus>:<slot>:<function>, example: 0000:84:00:0', max_length=100)),
                ('vm', models.CharField(blank=True, max_length=200, null=True)),
                ('attach_time', models.DateTimeField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute.Host')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': '1_GPU',
            },
        ),
    ]
