# Generated by Django 3.2.13 on 2022-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20191202_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcidevice',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='启用设备'),
        ),
    ]
