# Generated by Django 3.2.13 on 2023-07-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_pcidevice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcidevice',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '未知设备'), (1, 'PCIeGPU'), (2, 'PCIe网卡'), (3, 'PCIe硬盘'), (4, '本地硬盘')], default=0, verbose_name='资源类型'),
        ),
    ]
