# Generated by Django 2.2.6 on 2019-11-01 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0002_auto_20191024_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
