# Generated by Django 2.2.16 on 2020-12-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0004_host_real_cpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='vlans',
        ),
    ]
