# Generated by Django 3.2.13 on 2022-07-13 11:29

from django.db import migrations, models
import django.db.models.deletion

def update_host_unit_mb_to_gb(apps, schema_editor):
    Host = apps.get_model("compute","Host")
    hosts = Host.objects.all()
    for host in hosts:
        host.real_mem = host.mem_total/1024
        host.mem_total = (host.mem_total-host.mem_reserved)/1024
        host.mem_allocated = host.mem_allocated / 1024
        host.save()
    print('changed host unit ', len(hosts), 'records')

def construct_relation_between_host_and_pcserver(apps, schema_editor):
    Host = apps.get_model("compute","Host")
    PcServer = apps.get_model("pcservers","PcServer")

    hosts = Host.objects.all()
    for host in hosts:
        try:
            host.pcserver = PcServer.objects.get(host_ipv4 = host.ipv4)
        except PcServer.DoesNotExist:
            host.pcserver = None
        host.save()
    print('changed host unit ', len(hosts), 'records')

class Migration(migrations.Migration):

    dependencies = [
        ('pcservers', '0002_remove_pcserver_host'),
        ('compute', '0005_remove_host_vlans'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='pcserver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='pc_server_host', to='pcservers.pcserver', verbose_name='物理服务器'),
        ),
        migrations.AddField(
            model_name='host',
            name='real_mem',
            field=models.IntegerField(default=30, verbose_name='真实物理内存大小(Gb)'),
        ),
        migrations.RunPython(update_host_unit_mb_to_gb),
        migrations.RemoveField(
            model_name='host',
            name='mem_reserved',
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_allocated',
            field=models.IntegerField(default=0, verbose_name='宿主机已分配内存大小(Gb)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_total',
            field=models.IntegerField(default=30, verbose_name='宿主机可用内存大小(Gb)'),
        ),
        migrations.RunPython(construct_relation_between_host_and_pcserver),
    ]
