# Generated by Django 3.2.13 on 2023-02-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0007_auto_20220919_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mem_allocated',
            field=models.IntegerField(default=0, verbose_name='已用内存(GB)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_total',
            field=models.IntegerField(default=30, verbose_name='虚拟内存(GB)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='real_cpu',
            field=models.IntegerField(default=20, verbose_name='真实物理CPU(核)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='real_mem',
            field=models.IntegerField(default=30, verbose_name='真实物理内存(Gb)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vcpu_allocated',
            field=models.IntegerField(default=0, verbose_name='已用CPU（核）'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vcpu_total',
            field=models.IntegerField(default=24, verbose_name='虚拟CPU(核）'),
        ),
    ]
