# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField()),
                ('host_ipv4', models.GenericIPAddressField()),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '宿主机故障记录',
                'verbose_name_plural': '1_宿主机故障记录',
            },
        ),
        migrations.CreateModel(
            name='VmMigrateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_error_log_id', models.IntegerField(help_text='引起虚拟机迁移的宿主机故障记录', null=True)),
                ('vm_uuid', models.CharField(max_length=100, unique=True)),
                ('vm_ipv4', models.GenericIPAddressField()),
                ('src_host_ipv4', models.GenericIPAddressField()),
                ('dst_host_ipv4', models.GenericIPAddressField()),
                ('migrate_res', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '高可用虚拟机迁移记录',
                'verbose_name_plural': '2_高可用虚拟机迁移记录',
            },
        ),
    ]
