# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点显示名称')),
                ('pro_enable', models.BooleanField(default=False, verbose_name='开启高阶功能')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置列表',
            },
        ),
    ]
