# Generated by Django 2.2.10 on 2020-06-01 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0004_host_real_cpu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='部门编号')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='机房名称')),
                ('city', models.CharField(max_length=255, verbose_name='所在城市')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='型号')),
                ('desc', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '服务器型号',
                'verbose_name_plural': '服务器型号',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PcServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '使用中'), (2, '外借'), (3, '盘亏'), (4, '空闲'), (5, '故障'), (6, '已报废'), (7, '其他')], default=1, verbose_name='状态')),
                ('buy_time', models.DateTimeField(blank=True, null=True, verbose_name='购买时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('due_time', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('tag_no', models.CharField(max_length=255, verbose_name='标签号/序列号')),
                ('location', models.CharField(max_length=255, verbose_name='所在位置')),
                ('host_ipv4', models.CharField(max_length=100, verbose_name='主机IPv4地址')),
                ('ipmi_ip', models.CharField(max_length=100, verbose_name='IPMI管理地址')),
                ('host_ipv6', models.CharField(blank=True, default='', max_length=100, verbose_name='主机IPv6地址')),
                ('ipmi_ipv6', models.CharField(blank=True, default='', max_length=100, verbose_name='IPMI管理ipv6地址')),
                ('user', models.CharField(max_length=100, verbose_name='使用人')),
                ('use_for', models.TextField(blank=True, default='', verbose_name='用途')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('hardware_info', models.TextField(blank=True, default='', verbose_name='硬件配置信息')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_server', to=settings.AUTH_USER_MODEL, verbose_name='联系人')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcservers.Department', verbose_name='部门')),
                ('host', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_server', to='compute.Host', verbose_name='宿主机')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_server', to='pcservers.Room', verbose_name='所在机房')),
                ('server_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_server', to='pcservers.ServerType', verbose_name='型号')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'ordering': ['id'],
            },
        ),
    ]
