# Generated by Django 3.2.13 on 2022-07-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcservers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcserver',
            name='host',
        ),
    ]
