# Generated by Django 3.2.13 on 2022-08-17 03:25

from django.db import migrations, models
import django.db.models.deletion

def update_pc_server_mem_and_cpu(apps, schema_editor):
    Host = apps.get_model("compute", "Host")
    hosts = Host.objects.all()
    changed = 0
    for host in hosts:
        if host.pcserver:
            host.pcserver.real_mem = host.real_mem
            host.pcserver.real_cpu = host.real_cpu
            host.pcserver.save()
            changed = changed + 1
    print('changed pc_server ', changed, ' records')

class Migration(migrations.Migration):

    dependencies = [
        ('pcservers', '0002_remove_pcserver_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcserver',
            name='real_cpu',
            field=models.IntegerField(default=20, verbose_name='真实物理CPU总数'),
        ),
        migrations.AddField(
            model_name='pcserver',
            name='real_mem',
            field=models.IntegerField(default=30, verbose_name='真实物理内存大小(Gb)'),
        ),
        migrations.RunPython(update_pc_server_mem_and_cpu),
    ]
