# Generated by Django 2.2.6 on 2019-10-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('ip', models.CharField(max_length=64, verbose_name='宿主机ip')),
                ('port', models.CharField(max_length=32, verbose_name='vnc端口')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'novnc tokens',
                'verbose_name_plural': 'novnc tokens',
            },
        ),
    ]
