# Generated by Django 2.2.7 on 2019-12-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novnc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='token',
            name='expiretime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
