# Generated by Django 2.2.6 on 2019-11-06 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'verbose_name': '云硬盘CEPH存储池', 'verbose_name_plural': '云硬盘CEPH存储池'},
        ),
        migrations.AlterModelOptions(
            name='vdisk',
            options={'verbose_name': 'CEPH云硬盘', 'verbose_name_plural': 'CEPH云硬盘'},
        ),
        migrations.RemoveField(
            model_name='quota',
            name='vdisk',
        ),
        migrations.AddField(
            model_name='quota',
            name='max_vdisk',
            field=models.IntegerField(default=200, help_text='单位GB', verbose_name='云硬盘最大容量(GB)'),
        ),
        migrations.AddField(
            model_name='quota',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='存储池名称'),
        ),
        migrations.AddField(
            model_name='quota',
            name='size_used',
            field=models.IntegerField(default=0, help_text='单位GB', verbose_name='已使用容量(GB)'),
        ),
        migrations.AddField(
            model_name='vdisk',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vdisk_set', to='vdisk.Quota', verbose_name='云硬盘CEPH存储池'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='cephpool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_set', to='ceph.CephPool', verbose_name='CEPH存储池'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_set', to='compute.Group', verbose_name='宿主机组'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='total',
            field=models.IntegerField(default=0, help_text='单位GB', verbose_name='可用总容量(GB)'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='attach_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='挂载时间'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='dev',
            field=models.CharField(blank=True, default='', editable=False, help_text='对应系统中硬盘挂载逻辑设备名称（vda-vdz）', max_length=100, verbose_name='虚拟机中disk的设备名称'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='size',
            field=models.IntegerField(help_text='单位GB', verbose_name='容量大小GB'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vdisk_set', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='云硬盘UUID'),
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='vm',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='挂载于虚拟机'),
        ),
        migrations.AlterUniqueTogether(
            name='vdisk',
            unique_together={('uuid', 'quota')},
        ),
        migrations.RemoveField(
            model_name='vdisk',
            name='cephpool',
        ),
        migrations.RemoveField(
            model_name='vdisk',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='vdisk',
            name='group',
        ),
    ]
