# Generated by Django 2.2.7 on 2019-11-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdisk', '0002_auto_20191106_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vdisk',
            options={'ordering': ['-create_time'], 'verbose_name': 'CEPH云硬盘', 'verbose_name_plural': 'CEPH云硬盘'},
        ),
        migrations.AlterField(
            model_name='vdisk',
            name='vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vdisk_set', to='vms.Vm', verbose_name='挂载于虚拟机'),
        ),
        migrations.AddField(
            model_name='vdisk',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
