# Generated by Django 3.2.4 on 2021-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdisk', '0003_auto_20191112_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdisk',
            name='rbd_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ceph rbd name'),
        ),
    ]
