# Generated by Django 3.2.13 on 2023-06-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdisk', '0004_vdisk_rbd_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='enable',
            field=models.BooleanField(default=True, help_text='开启和暂停使用2中状态, 未开启使用不允许创建云硬盘时', verbose_name='存储池是否可用'),
        ),
    ]
