# Generated by Django 4.2.9 on 2024-04-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, default=0, verbose_name='状态码')),
                ('method', models.CharField(blank=True, default='', max_length=32, verbose_name='请求方法')),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, '添加'), (2, '修改'), (3, '删除'), (4, '查询'), (5, '重建')], default=None, verbose_name='操作')),
                ('operation_content', models.CharField(default=None, max_length=255, verbose_name='操作内容')),
                ('resourc_type', models.PositiveSmallIntegerField(choices=[(6, '云主机'), (7, 'VPN'), (8, '云硬盘')], default=None, verbose_name='资源类型')),
                ('full_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='请求路径')),
                ('message', models.TextField(blank=True, default='', verbose_name='日志信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='请求用户')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'log_record_user',
                'ordering': ['-create_time'],
            },
        ),
    ]
