# Generated by Django 4.2.9 on 2024-04-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrecord', '0002_alter_logrecord_action_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='action_flag',
        ),
        migrations.RemoveField(
            model_name='logrecord',
            name='resourc_type',
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='请求用户'),
        ),
    ]
