# Generated by Django 4.2.9 on 2024-04-29 07:29

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('logrecord', '0003_remove_logrecord_action_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='real_user',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='cstcloud用户'),
        ),
    ]
