# Generated by Django 4.2.9 on 2024-04-29 07:29

from django.db import migrations, models


def log_real_user_add(apps, schema_editor):
    log_model = apps.get_model('logrecord', 'LogRecord')
    log_objs = log_model.objects.all()
    for log_obj in log_objs:
        try:
            if log_obj.real_user is '':
                log_obj.real_user = log_obj.username
                log_obj.save(update_fields=['real_user'])
        except Exception as e:
            print(f'迁移用户操作日志文件，修改real_user信息错误：{str(e)}')
            pass


def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('logrecord', '0003_remove_logrecord_action_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='real_user',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='cstcloud用户'),
        ),
        migrations.RunPython(log_real_user_add, reverse_code=do_nothing),
    ]
