# Generated by Django 4.2.9 on 2024-05-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrecord', '0004_logrecord_real_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='request_ip',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='IP信息'),
        ),
    ]
