# Generated by Django 2.2.6 on 2019-10-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephCluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('uuid', models.CharField(help_text='xml中ceph配置的uuid,libvirt通过uuid获取访问ceph的用户key', max_length=50, verbose_name='xml中ceph的uuid')),
                ('config', models.TextField(default='', verbose_name='ceph集群配置文本')),
                ('config_file', models.CharField(blank=True, editable=False, help_text='点击保存，配置文本会存储到这个文件, 此字段自动填充', max_length=200, verbose_name='配置文件保存路径')),
                ('keyring', models.TextField(verbose_name='ceph集群keyring文本')),
                ('keyring_file', models.CharField(blank=True, editable=False, help_text='点击保存，keyring文本会存储到这个文件, 此字段自动填充', max_length=200, verbose_name='keyring文件保存路径')),
                ('hosts_xml', models.TextField(help_text="设置虚机xml中disk/source元素的ceph monitors信息，格式:&lt;host name='10.100.50.1' port='6789'/&gt;", null=True, verbose_name='ceph monitors')),
                ('username', models.CharField(default='admin', help_text='ceph用户名，需与keyring文件一致', max_length=100, verbose_name='ceph用户名')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceph_clusters', to='compute.Center', verbose_name='所属数据中心')),
            ],
            options={
                'verbose_name': 'ceph cluster',
                'verbose_name_plural': 'ceph cluster',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CephPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pool_name', models.CharField(max_length=100, verbose_name='POOL名称')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('ceph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceph.CephCluster')),
            ],
            options={
                'verbose_name': 'ceph pool',
                'verbose_name_plural': 'ceph pool',
                'ordering': ('id',),
            },
        ),
    ]
