# Generated by Django 2.2.9 on 2020-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cephpool',
            name='data_pool',
            field=models.CharField(default='', max_length=100, verbose_name='数据存储POOL名称'),
        ),
        migrations.AddField(
            model_name='cephpool',
            name='has_data_pool',
            field=models.BooleanField(default=False, verbose_name='是否有独立存储POOL'),
        ),
    ]
