# Generated by Django 2.2.9 on 2020-02-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0002_auto_20200121_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cephcluster',
            name='has_auth',
            field=models.BooleanField(default=True, help_text='未选中时，不使用uuid字段，uuid设置为空', verbose_name='是否需要认证'),
        ),
        migrations.AlterField(
            model_name='cephcluster',
            name='uuid',
            field=models.CharField(blank=True, help_text='xml中ceph配置的uuid,libvirt通过uuid获取访问ceph的用户key', max_length=50, verbose_name='xml中ceph的uuid'),
        ),
    ]
