# Generated by Django 3.2.13 on 2023-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0003_auto_20200211_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('sitename', models.CharField(default='EVcloud', max_length=50, verbose_name='站点名称')),
                ('poweredby', models.CharField(default='https://gitee.com/cstcloud-cnic/evcloud', max_length=255, verbose_name='技术支持')),
                ('novnchttp', models.CharField(default='http', help_text='配置novnchttp协议 http/https', max_length=10, verbose_name='novnc http协议配置')),
            ],
            options={
                'verbose_name': '全局配置表',
                'verbose_name_plural': '全局配置表',
                'db_table': 'site_global_config',
                'ordering': ['-id'],
            },
        ),
    ]
