# Generated by Django 4.2.9 on 2024-04-09 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0005_globalconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='novnchttp',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='poweredby',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='sitename',
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='content',
            field=models.CharField(default='', max_length=255, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='modif_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, '站点'), (2, '技术支持'), (3, 'novnchttp')], default=None, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
