# Generated by Django 4.2.9 on 2024-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0006_remove_globalconfig_novnchttp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='内容'),
        ),
    ]
