# Generated by Django 4.2.9 on 2024-05-07 01:30

from django.db import migrations, models


def initialize_add_data(apps, schema_editor):
    ip_cls = apps.get_model('ceph', 'ApiAllowIP')
    ip_qs = ip_cls.objects.all()
    if ip_qs:
        return
    ip_cls.objects.create(ip_value='0.0.0.0/0', remark='初始化设置：允许所有IP访问，如果添加其他IP信息请删除此IP')
    return

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0007_alter_globalconfig_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAllowIP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_value', models.CharField(help_text='192.168.1.1、 192.168.1.1/24、192.168.1.66 - 192.168.1.100', max_length=100, verbose_name='IP')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '管理员IP白名单',
                'verbose_name_plural': '管理员IP白名单',
                'db_table': 'app_global_parameter_apiallowip',
                'ordering': ['-creation_time'],
            },
        ),

        migrations.RunPython(initialize_add_data, reverse_code=do_nothing),
    ]
